BACKGROUND_FILE_PATH: "../data/background/original"
#SAMPLE_FILES_PATH: "../data/GermanFlag"
#OUTPUT_PATH: "../data/GermanFlag/augmentedFiles"
#SAMPLE_FILES_PATH: "../data/my/idc_back"
#OUTPUT_PATH: "../data/my/idc_back/augmentedFiles"
SAMPLE_FILES_PATH: "../data/my/idc_front"
OUTPUT_PATH: "../data/my/idc_front/augmentedFiles"
BACKGROUND_COLOR : 255
BACKGROUND_THRESH : 8
MAX_X_ANGLE: 3
MAX_Y_ANGLE: 3
MAX_Z_ANGLE: 3
MAX_AFFINE_ANGLE: 3
AFFINE_ROT_PROB: 0.4
PERSP_TRANS_PROB: 0.3
GAUSS_NOISE_PROB: 0.4
MEDIAN_NOISE_PROB: 0.4
SHARPEN_PROB: 0.3
OUTPUT_PER_SAMPLE: 3
SCALING_PROB: 0.6
BRIGHTNESS_PROB: 0.5
